### ISSUE TITLE
Invalid object name "revenue0". SQL queries No. 15

### ISSUE THREAD

**Issue by Pro100MIX** [huunghia160799/TPC-H-Dataset-Generator-MS-SQL-Server#1]
There was a problem when running query 15.
I tried to run with this method on MS SQL Server Management Studio 18:

```
create view revenue0 (supplier_no, total_revenue) as
    select
        l_suppkey,
        sum(l_extendedprice * (1 - l_discount))
    from
        lineitem
    where
        l_shipdate >= cast('1996-05-01' as datetime)
        and l_shipdate < dateadd(mm, 3, cast('1996-05-01' as datetime))
    group by
        l_suppkey;
go
select
    s_suppkey,
    s_name,
    s_address,
    s_phone,
    total_revenue
from
    supplier,
    revenue0
where
    s_suppkey = supplier_no
    and total_revenue = (
        select
            max(total_revenue)
        from
            revenue0
    )
order by
    s_suppkey;

drop view revenue0; 
``` 

But as a result of executing the request, an error is displayed: Invalid object name "revenue0". As soon as I didn't change my name. SQL all the same swears at this name.

How can I fix this?! Please, help!

**Comment by nghiahhnguyen** [comment]
Can you try creating the view first using

```
create view revenue0 (supplier_no, total_revenue) as
    select
        l_suppkey,
        sum(l_extendedprice * (1 - l_discount))
    from
        lineitem
    where
        l_shipdate >= cast('1996-05-01' as datetime)
        and l_shipdate < dateadd(mm, 3, cast('1996-05-01' as datetime))
    group by
        l_suppkey;
go
```

before running a simple query to check out if the view is created. For example

```
select * from revenue0;
```

If the view is created successfully after running the first part then there should not be any problem.

**Comment by Pro100MIX** [comment]
> Can you try creating the view first using
> 
> ```
> create view revenue0 (supplier_no, total_revenue) as
>     select
>         l_suppkey,
>         sum(l_extendedprice * (1 - l_discount))
>     from
>         lineitem
>     where
>         l_shipdate >= cast('1996-05-01' as datetime)
>         and l_shipdate < dateadd(mm, 3, cast('1996-05-01' as datetime))
>     group by
>         l_suppkey;
> go
> ```
> 
> before running a simple query to check out if the view is created. For example
> 
> ```
> select * from revenue0;
> ```
> 
> If the view is created successfully after running the first part then there should not be any problem.

Yes, it worked. I don’t know what could have been a mistake. But the request was successful.
Thank you very much!
