### ISSUE TITLE
missing utils in gen_queries.py

### ISSUE THREAD

**Issue by jackyromano** [huunghia160799/TPC-H-Dataset-Generator-MS-SQL-Server#3]
I get the following error message:
```$ python3 gen_queries.py
Traceback (most recent call last):
  File "gen_queries.py", line 8, in <module>
    from utils import extract_tables_columns
ModuleNotFoundError: No module named 'utils'
```
What am I missing?

Thanks in advance,
Jacky

**Comment by nghiahhnguyen** [comment]
Oh after I've checked, it's importing something unused. Can you try commenting out ```from utils import extract_tables_columns``` and see if it's alright?

**Comment by jackyromano** [comment]
Yep, this solved the issue.
Thanks
